#!/usr/bin/env python3
"""Generate `h5reader_manifest.toml` for an existing input directory.

The h5-reader loader's documented contract for an input directory is the
manifest at the directory root (see `spec/INPUT_DIRECTORY.md`). Existing
fixtures predate the manifest; this tool walks the conventional layout
that the loader's legacy fallback recognises and writes the equivalent
manifest, so those fixtures can be opened without the "no manifest"
deprecation warning.

Detection rules (no glob, no fuzzy match — only the canonical names the
loader's legacy fallback checks):

  Trajectory run:
    <root>/trajectory.h5                 OR
    <root>/extract/trajectory.h5
    The sidecar dir is the directory containing trajectory.h5.
    Per-frame snapshots: <sidecar>/per_frame_npys then <sidecar>/npys.

  Single pose:
    <root>/atoms_category_info.npy       (the sidecar's anchor file)
    The pose_dir is the root itself.

  Optional dft jobs: <root>/dft/jobs

  Optional reference PDB: <sidecar>/reference.pdb

Mutant pairs cannot be auto-detected (the layout is ambiguous —
two single-pose dirs side by side). For mutant pairs, write the
manifest by hand or use `--mutant-pair WT_DIR ALA_DIR`.

Usage:
  python3 generate_manifest.py <run_root>
  python3 generate_manifest.py --mutant-pair <wt_dir> <ala_dir> --root <root>
  python3 generate_manifest.py --dry-run <run_root>     # print, don't write
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path


def _find_trajectory_h5(root: Path) -> tuple[Path, Path] | None:
    """Return (trajectory_h5, sidecar_dir) or None."""
    direct = root / "trajectory.h5"
    if direct.is_file():
        return (direct, root)
    extract = root / "extract" / "trajectory.h5"
    if extract.is_file():
        return (extract, root / "extract")
    return None


def _find_per_frame_npys(sidecar_dir: Path) -> Path | None:
    for name in ("per_frame_npys", "npys"):
        candidate = sidecar_dir / name
        if candidate.is_dir():
            return candidate
    return None


def _looks_like_single_pose(root: Path) -> bool:
    return (root / "atoms_category_info.npy").is_file()


def _read_protein_id(sidecar_dir: Path) -> str | None:
    """Best-effort: read protein_id from extraction_manifest.json."""
    manifest = sidecar_dir / "extraction_manifest.json"
    if not manifest.is_file():
        return None
    try:
        with manifest.open() as f:
            data = json.load(f)
        pid = data.get("protein_id")
        if isinstance(pid, str) and pid:
            return pid
    except (json.JSONDecodeError, OSError) as e:
        print(f"  warning: could not read protein_id from {manifest}: {e}",
              file=sys.stderr)
    return None


def _toml_string(s: str) -> str:
    """Quote a string the TOML way (basic escaping only — we control inputs)."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _relpath(target: Path, base: Path) -> str:
    """Return target relative to base, using forward slashes (cross-platform)."""
    try:
        rel = target.resolve().relative_to(base.resolve())
        return str(rel).replace("\\", "/")
    except ValueError:
        # Outside base — fall back to absolute.
        return str(target.resolve()).replace("\\", "/")


def detect_trajectory(root: Path) -> dict | None:
    h5_hit = _find_trajectory_h5(root)
    if h5_hit is None:
        return None
    trajectory_h5, sidecar_dir = h5_hit
    per_frame = _find_per_frame_npys(sidecar_dir)
    return {
        "kind": "trajectory",
        "protein_id": _read_protein_id(sidecar_dir) or root.name,
        "trajectory_h5": _relpath(trajectory_h5, root),
        "topology_sidecar_dir": _relpath(sidecar_dir, root),
        "per_frame_npys_dir": _relpath(per_frame, root) if per_frame else None,
    }


def detect_single_pose(root: Path) -> dict | None:
    if not _looks_like_single_pose(root):
        return None
    return {
        "kind": "single_pose",
        "protein_id": _read_protein_id(root) or root.name,
        "pose_dir": "./",
    }


def detect_dft_and_reference(root: Path, sidecar_dir: Path | None) -> dict:
    out: dict = {}
    dft_jobs = root / "dft" / "jobs"
    if dft_jobs.is_dir():
        out["dft_jobs_dir"] = _relpath(dft_jobs, root)
    if sidecar_dir:
        ref_pdb = sidecar_dir / "reference.pdb"
        if ref_pdb.is_file():
            out["reference_pdb"] = _relpath(ref_pdb, root)
    return out


def render_manifest(detected: dict, root: Path,
                    mutant_pair: tuple[Path, Path] | None = None) -> str:
    """Format the manifest as TOML text."""
    lines: list[str] = []
    lines.append("# h5reader_manifest.toml — generated by tools/generate_manifest.py")
    lines.append(f"# Generated for {root.name} at {dt.datetime.now(dt.UTC).isoformat(timespec='seconds')}")
    lines.append("# See h5-reader/spec/INPUT_DIRECTORY.md for the schema.")
    lines.append("")
    lines.append("schema_version = 1")
    if mutant_pair is not None:
        lines.append('run_kind       = "mutant_pair"')
        lines.append(f"protein_id     = {_toml_string(detected['protein_id'])}")
        lines.append("")
        wt_dir, ala_dir = mutant_pair
        lines.append("[mutant_pair]")
        lines.append(f"wt_pose_dir  = {_toml_string(_relpath(wt_dir, root))}")
        lines.append(f"ala_pose_dir = {_toml_string(_relpath(ala_dir, root))}")
    elif detected["kind"] == "trajectory":
        lines.append('run_kind       = "trajectory"')
        lines.append(f"protein_id     = {_toml_string(detected['protein_id'])}")
        lines.append("")
        lines.append("[trajectory]")
        lines.append(f"trajectory_h5        = {_toml_string(detected['trajectory_h5'])}")
        lines.append(f"topology_sidecar_dir = {_toml_string(detected['topology_sidecar_dir'])}")
        if detected.get("per_frame_npys_dir"):
            lines.append(f"per_frame_npys_dir   = {_toml_string(detected['per_frame_npys_dir'])}")
    elif detected["kind"] == "single_pose":
        lines.append('run_kind       = "single_pose"')
        lines.append(f"protein_id     = {_toml_string(detected['protein_id'])}")
        lines.append("")
        lines.append("[single_pose]")
        lines.append(f"pose_dir = {_toml_string(detected['pose_dir'])}")
    else:
        raise ValueError(f"unknown detected kind: {detected['kind']!r}")

    extras = detected.get("extras", {})
    if extras.get("dft_jobs_dir"):
        lines.append("")
        lines.append("[dft]")
        lines.append(f"jobs_dir = {_toml_string(extras['dft_jobs_dir'])}")
    if extras.get("reference_pdb"):
        lines.append("")
        lines.append(f"reference_pdb = {_toml_string(extras['reference_pdb'])}")

    lines.append("")
    lines.append("[metadata]")
    lines.append(f"extracted_at  = {dt.datetime.now(dt.UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    lines.append('fixture_kind  = "production"   # one of: calibration | production | test')
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("run_root", nargs="?", type=Path,
                   help="Root of the input directory to inspect / annotate.")
    p.add_argument("--mutant-pair", nargs=2, metavar=("WT_DIR", "ALA_DIR"),
                   type=Path,
                   help="Generate a mutant_pair manifest pointing at these two pose dirs.")
    p.add_argument("--root", type=Path,
                   help="Root the manifest is generated AT (required with --mutant-pair "
                        "if the WT/ALA dirs are siblings of the root).")
    p.add_argument("--dry-run", action="store_true",
                   help="Print the manifest to stdout instead of writing to disk.")
    p.add_argument("--force", action="store_true",
                   help="Overwrite an existing manifest at the target path.")
    args = p.parse_args(argv)

    if args.mutant_pair is not None:
        if args.root is None:
            print("error: --mutant-pair requires --root", file=sys.stderr)
            return 2
        wt_dir, ala_dir = args.mutant_pair
        root = args.root.resolve()
        if not wt_dir.is_dir() or not ala_dir.is_dir():
            print(f"error: --mutant-pair dirs must exist: WT={wt_dir} ALA={ala_dir}",
                  file=sys.stderr)
            return 2
        # protein_id: read from WT side; fall back to root name.
        protein_id = _read_protein_id(wt_dir) or root.name
        detected = {"kind": "mutant_pair", "protein_id": protein_id, "extras": {}}
        text = render_manifest(detected, root, mutant_pair=(wt_dir, ala_dir))
    else:
        if args.run_root is None:
            print("error: <run_root> is required (or use --mutant-pair)", file=sys.stderr)
            p.print_help(sys.stderr)
            return 2
        root = args.run_root.resolve()
        if not root.is_dir():
            print(f"error: {root} is not a directory", file=sys.stderr)
            return 2
        detected = detect_trajectory(root) or detect_single_pose(root)
        if detected is None:
            print(f"error: {root} does not look like an h5-reader input "
                  "(no trajectory.h5 in . or extract/, no atoms_category_info.npy in .)",
                  file=sys.stderr)
            return 3
        sidecar_dir = root / detected.get("topology_sidecar_dir", ".") if detected["kind"] == "trajectory" else root
        detected["extras"] = detect_dft_and_reference(root, sidecar_dir)
        text = render_manifest(detected, root)

    target = root / "h5reader_manifest.toml"
    if args.dry_run:
        print(text, end="")
        return 0
    if target.exists() and not args.force:
        print(f"error: {target} already exists; pass --force to overwrite", file=sys.stderr)
        return 4
    target.write_text(text)
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
