#!/usr/bin/env python3
"""Generate producer QtFieldCatalog.gen.h from python/nmr_extract/_catalog.py.

This is the h5-reader's producer no-strings load boundary. `_catalog.py`
is the SDK source of truth for producer-owned NPY arrays; reader-owned
rediscover/statistics sidecars are declared in
src/rediscover/ReaderOutputCatalog.h. This script mirrors the producer
CATALOG into a typed C++ table so the reader resolves a producer filename
stem to a typed FieldSpec exactly once (FindFieldByStem) and then
dispatches on the FieldKind / FieldGroup / NativeAxis enums.

Faithful-by-construction: it imports the finalized CATALOG object rather
than re-typing entries or parsing only its initial declaration. This is
important because _catalog.py deliberately completes many physical
contracts with dataclasses.replace() after the declaration. The generated
header is committed, so portable builds and installed readers never need
Python.

    python3 h5-reader/scripts/gen_field_catalog.py
    python3 h5-reader/scripts/gen_field_catalog.py --check

Re-run whenever _catalog.py changes; the FrameNpyLoader's load-time
guard cross-checks a real frame dir's files against the table so any
drift surfaces loudly.
"""

import argparse
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve()
ROOT = HERE.parents[2]  # .../nmr-shielding
CATALOG_PY = ROOT / "python" / "nmr_extract" / "_catalog.py"
OUT_H = ROOT / "h5-reader" / "src" / "io" / "QtFieldCatalog.gen.h"


# Physics/method acronyms so enumerators read like the library
# ("the name is the thing"): mc_shielding -> McShielding, hbond -> HBond,
# bs_per_type_T0 -> BSPerTypeT0. Tokens not listed get plain Title case.
_ACRONYMS = {
    "bs": "BS", "hm": "HM", "pq": "PQ", "mc": "Mc", "efg": "EFG",
    "dssp": "DSSP", "sasa": "SASA", "apbs": "APBS", "eeq": "EEQ",
    "cn": "CN", "bb": "BB", "mopac": "MOPAC", "aimnet2": "AIMNet2",
    "hbond": "HBond", "mcconnell": "McConnell", "ringchi": "RingChi",
}


def pascal(name: str) -> str:
    """snake_case (or mixed) -> PascalCase enumerator, acronym-aware."""
    return "".join(
        _ACRONYMS.get(part.lower(), part[:1].upper() + part[1:])
        for part in name.split("_")
    )


def cpp_str(s) -> str:
    s = "" if s is None else str(s)
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return '"' + escaped + '"'


def wrapper_name(wrapper: type) -> str:
    module = getattr(wrapper, "__module__", "")
    name = getattr(wrapper, "__name__", str(wrapper))
    return f"np.{name}" if module == "numpy" else name


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or verify the Reader's typed nmr_extract field catalog."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed generated header differs from current CATALOG",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sys.path.insert(0, str(ROOT / "python"))
    try:
        from nmr_extract._catalog import CATALOG
    except Exception as exc:
        print(f"ERROR: could not import finalized producer CATALOG: {exc}", file=sys.stderr)
        return 1

    entries = list(CATALOG.values())
    if list(CATALOG) != [entry.stem for entry in entries]:
        print("ERROR: CATALOG keys do not exactly match ArraySpec stems", file=sys.stderr)
        return 1

    enum_names = [pascal(entry.stem) for entry in entries]
    duplicates = sorted({name for name in enum_names if enum_names.count(name) > 1})
    if duplicates:
        print(f"ERROR: FieldKind enumerator collisions: {duplicates}", file=sys.stderr)
        return 1

    groups, axes = [], []
    for e in entries:
        if e.group not in groups:
            groups.append(e.group)
        ax = e.native_axis
        if ax not in axes:
            axes.append(ax)

    # Catalog identity must not depend on the checkout's CRLF/LF policy.
    catalog_text = CATALOG_PY.read_text(encoding="utf-8")
    catalog_text = catalog_text.replace("\r\n", "\n").replace("\r", "\n")
    digest = hashlib.sha256(catalog_text.encode("utf-8")).hexdigest()
    out = []
    w = out.append
    w("// QtFieldCatalog.gen.h - GENERATED by h5-reader/scripts/gen_field_catalog.py")
    w(f"// from {CATALOG_PY.relative_to(ROOT).as_posix()} (sha256 {digest})")
    w(f"// {len(entries)} fields / {len(groups)} groups / {len(axes)} axes. DO NOT EDIT BY HAND.")
    w("// Regenerate: python3 h5-reader/scripts/gen_field_catalog.py")
    w("//")
    w("// The producer no-strings load boundary. A producer filename stem is resolved")
    w("// to a typed FieldSpec exactly once (FindFieldByStem); reader-owned sidecars")
    w("// are declared in rediscover/ReaderOutputCatalog.h. wrapper/irreps/units/")
    w("// mechanism are interop + display metadata, never identity.")
    w("#pragma once")
    w("#include <array>")
    w("#include <cstdint>")
    w("#include <optional>")
    w("#include <string_view>")
    w("")
    w("namespace h5reader::io {")
    w("")
    w("enum class FieldKind : std::int16_t {")
    for e in entries:
        w(f"    {pascal(e.stem)},")
    w("    Count")
    w("};")
    w("")
    w("enum class FieldGroup : std::int8_t {")
    for g in groups:
        w(f"    {pascal(g)},")
    w("};")
    w("")
    w("enum class NativeAxis : std::int8_t {")
    for ax in axes:
        w(f"    {pascal(ax)},")
    w("};")
    w("")
    w("struct FieldSpec {")
    w("    FieldKind kind;")
    w("    std::string_view stem;        // identity at the boundary, resolved once")
    w("    FieldGroup group;")
    w("    NativeAxis axis;")
    w("    int cols;                     // -1 = variable / 1-D (None in _catalog.py)")
    w("    bool required;")
    w("    std::int8_t tensor_rank;")
    w("    std::string_view parity;      // even, odd, or mixed")
    w("    std::string_view description;")
    w("    std::string_view wrapper;     // Python wrapper class name (shape hint)")
    w("    std::string_view irreps;      // legacy hint; explicit export contract wins")
    w("    std::string_view units;")
    w("    std::string_view sign_convention;")
    w("    std::string_view mechanism;")
    w("    std::string_view tensor_basis;")
    w("    std::string_view tensor_component_order;")
    w("    std::string_view tensor_frame;")
    w("    std::string_view structural_zero_components;")
    w("    std::string_view e3nn_export;")
    w("    std::string_view scaling_contract;")
    w("    std::string_view coordinate_frame;")
    w("    std::string_view transformation;")
    w("    std::string_view validity;")
    w("};")
    w("")
    w(f"inline constexpr std::array<FieldSpec, {len(entries)}> kFieldCatalog = {{{{")
    for e in entries:
        cols = -1 if e.cols is None else int(e.cols)
        req = "true" if e.required else "false"
        w(f"    {{ FieldKind::{pascal(e.stem)}, {cpp_str(e.stem)}, "
          f"FieldGroup::{pascal(e.group)}, NativeAxis::{pascal(e.native_axis)}, "
          f"{cols}, {req}, {int(e.tensor_rank)}, {cpp_str(e.parity)}, "
          f"{cpp_str(e.description)}, {cpp_str(wrapper_name(e.wrapper))}, "
          f"{cpp_str(e.irreps)}, {cpp_str(e.units)}, {cpp_str(e.sign_convention)}, "
          f"{cpp_str(e.mechanism)}, {cpp_str(e.tensor_basis)}, "
          f"{cpp_str(e.tensor_component_order)}, {cpp_str(e.tensor_frame)}, "
          f"{cpp_str(e.structural_zero_components)}, {cpp_str(e.e3nn_export)}, "
          f"{cpp_str(e.scaling_contract)}, {cpp_str(e.coordinate_frame)}, "
          f"{cpp_str(e.transformation)}, {cpp_str(e.validity)} }},")
    w("}};")
    w("")
    w(f"// Boundary lookup: stem -> FieldKind. Linear scan over {len(entries)} entries, called")
    w("// once per NPY at load time. The ONE place a filename string is compared.")
    w("inline std::optional<FieldKind> FindFieldByStem(std::string_view stem) {")
    w("    for (const auto& fs : kFieldCatalog)")
    w("        if (fs.stem == stem) return fs.kind;")
    w("    return std::nullopt;")
    w("}")
    w("")
    w("// kFieldCatalog is emitted in FieldKind order, so the ordinal indexes it.")
    w("inline const FieldSpec& FieldSpecFor(FieldKind k) {")
    w("    return kFieldCatalog[static_cast<std::size_t>(k)];")
    w("}")
    w("")
    w("}  // namespace h5reader::io")
    w("")

    generated = "\n".join(out)
    if args.check:
        if not OUT_H.is_file():
            print(f"ERROR: generated header is missing: {OUT_H}", file=sys.stderr)
            return 1
        committed = OUT_H.read_text(encoding="utf-8")
        if committed != generated:
            print(
                "ERROR: QtFieldCatalog.gen.h is stale; run "
                "python h5-reader/scripts/gen_field_catalog.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"verified {OUT_H.relative_to(ROOT)}: "
            f"{len(entries)} fields, {len(groups)} groups, {len(axes)} axes"
        )
        return 0

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(ROOT)}: "
          f"{len(entries)} fields, {len(groups)} groups, {len(axes)} axes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
