// ReaderOutputCatalog -- reader-owned NPY sidecar contract.
//
// This is intentionally separate from python/nmr_extract/_catalog.py. The SDK
// catalog describes producer outputs; these arrays are emitted by h5reader's
// rediscover/statistics reader pass and are documented at the reader boundary.

#pragma once

#include "Aimnet2FeatureSink.h"
#include "AllAtomEquivariantSink.h"
#include "PerAtomSubstrate.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace h5reader::rediscover {

enum class ReaderOutputProducer : std::int8_t {
    RingCurrent,
    McConnell,
    ChargeDipole,
    BroadBackbone,
    PerAtomSubstrate,
    AllAtomEquivariant,
    Efg,
    BuckinghamEfield,
    Aimnet2Features,
    AnalysisObject,
};

enum class ReaderOutputAxis : std::int8_t {
    SourceRow,
    AggregatedRow,
    PerAtomRow,
    TargetRow,
    AtomRow,
};

enum class ReaderOutputRank : std::int8_t { Rank1 = 1, Rank2 = 2, Rank3 = 3 };
enum class ReaderOutputDtype : std::int8_t { F64, F32, I32, JsonObject };

struct ReaderOutputSpec {
    std::string_view stem;
    ReaderOutputProducer produced_by;
    ReaderOutputAxis native_axis;
    ReaderOutputRank rank;
    std::size_t extent0;
    std::size_t extent1;
    ReaderOutputDtype dtype;
    std::string_view irreps;
    std::int8_t tensor_rank;
    bool parity_odd;
    std::string_view units;
    std::string_view mechanism;
    std::string_view purpose;
};

constexpr std::size_t kReaderT2Cols = 5;
constexpr std::size_t kReaderVec3Cols = 3;
constexpr std::size_t kReaderMatrixRows = 3;
constexpr std::size_t kReaderMatrixCols = 3;

inline constexpr std::array<ReaderOutputSpec, 92> kReaderOutputCatalog = {{
    {"rediscover_ring_current_sources_target_T2",
     ReaderOutputProducer::RingCurrent,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "source-level lab-frame DFT T2 target for ring-current source audits and parity"},
    {"rediscover_ring_current_sources_target_local_T2",
     ReaderOutputProducer::RingCurrent,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "source-level local-frame DFT T2 target for ring-current geometry/kernel recovery"},
    {"rediscover_ring_current_sources_bare_kernel_T2",
     ReaderOutputProducer::RingCurrent,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm_T_per_nA",
     "ring_current",
     "source-level producer bare ring-current T2 kernel for source audits/future fits"},
    {"rediscover_ring_current_aggregated_target_T2",
     ReaderOutputProducer::RingCurrent,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row lab-frame DFT T2 target for ring-current aggregate law checks"},
    {"rediscover_ring_current_aggregated_target_local_T2",
     ReaderOutputProducer::RingCurrent,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row local-frame DFT T2 target preserving the local-frame contract"},
    {"rediscover_ring_current_aggregated_bare_kernel_T2",
     ReaderOutputProducer::RingCurrent,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm_T_per_nA",
     "ring_current",
     "aggregate producer bare Johnson-Bovey/ring-current T2 kernel"},

    {"rediscover_mcconnell_sources_target_T2",
     ReaderOutputProducer::McConnell,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "source-level lab-frame DFT T2 target for McConnell bond-source audits"},
    {"rediscover_mcconnell_sources_target_local_T2",
     ReaderOutputProducer::McConnell,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "source-level local-frame DFT T2 target for McConnell bond-source audits"},
    {"rediscover_mcconnell_sources_bare_kernel_T2",
     ReaderOutputProducer::McConnell,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "Angstrom^-3",
     "bond_anisotropy",
     "source-level producer bare McConnell T2 kernel"},
    {"rediscover_mcconnell_aggregated_target_T2",
     ReaderOutputProducer::McConnell,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row lab-frame DFT T2 target for McConnell comparisons"},
    {"rediscover_mcconnell_aggregated_target_local_T2",
     ReaderOutputProducer::McConnell,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row local-frame DFT T2 target preserving frame-complete output"},
    {"rediscover_mcconnell_aggregated_bare_kernel_T2",
     ReaderOutputProducer::McConnell,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "Angstrom^-3",
     "bond_anisotropy",
     "aggregate producer bare McConnell literature T2 kernel"},

    {"rediscover_charge_dipole_sources_target_T2",
     ReaderOutputProducer::ChargeDipole,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "source-level lab-frame DFT T2 target aligned to charge-source rows"},
    {"rediscover_charge_dipole_sources_target_local_T2",
     ReaderOutputProducer::ChargeDipole,
     ReaderOutputAxis::SourceRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "source-level local-frame DFT T2 target aligned to charge-source rows"},
    {"rediscover_charge_dipole_aggregated_target_T2",
     ReaderOutputProducer::ChargeDipole,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row lab-frame DFT T2 target for charge-dipole diagnostics/future tensor fits"},
    {"rediscover_charge_dipole_aggregated_target_local_T2",
     ReaderOutputProducer::ChargeDipole,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row local-frame DFT T2 target for charge-dipole diagnostics/future tensor fits"},

    {"broad_backbone_aggregated_target_T2",
     ReaderOutputProducer::BroadBackbone,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row lab-frame DFT T2 target"},
    {"broad_backbone_aggregated_target_local_T2",
     ReaderOutputProducer::BroadBackbone,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "aggregate-row local-frame DFT T2 target for the broad equivariant fitter"},
    {"broad_backbone_aggregated_field_local",
     ReaderOutputProducer::BroadBackbone,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "e/Angstrom^2",
     "charge_field",
     "local-frame summed heterogeneous electrostatic field/vector carrier"},
    {"broad_backbone_aggregated_literature_kernel_T2",
     ReaderOutputProducer::BroadBackbone,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "broad_backbone",
     "total broad literature T2 kernel, summing ring, bond, and charge legs"},
    {"broad_backbone_aggregated_ring_literature_kernel_T2",
     ReaderOutputProducer::BroadBackbone,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "ring_current",
     "ring-only literature T2 kernel contribution"},
    {"broad_backbone_aggregated_bond_literature_kernel_T2",
     ReaderOutputProducer::BroadBackbone,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "bond_anisotropy",
     "bond/McConnell-only literature T2 kernel contribution"},
    {"broad_backbone_aggregated_charge_literature_kernel_T2",
     ReaderOutputProducer::BroadBackbone,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "charge_field",
     "charge-only literature T2 kernel contribution"},

    {"per_atom_substrate_target_T2",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "total DFT shielding T2 target per atom/frame"},
    {"per_atom_substrate_target_T0",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "ppm",
     "dft_target",
     "total DFT isotropic shielding target"},
    {"per_atom_substrate_target_T1",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "ppm",
     "dft_target",
     "total DFT T1/axial vector diagnostic target"},
    {"per_atom_substrate_target_dia_T0",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "ppm",
     "dft_target",
     "diamagnetic isotropic target split, preserved for decomposition audits"},
    {"per_atom_substrate_target_dia_T1",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "ppm",
     "dft_target",
     "diamagnetic T1 target split, preserved for decomposition audits"},
    {"per_atom_substrate_target_dia_T2",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "diamagnetic T2 target split"},
    {"per_atom_substrate_target_para_T0",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "ppm",
     "dft_target",
     "paramagnetic isotropic target split, preserved for decomposition audits"},
    {"per_atom_substrate_target_para_T1",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "ppm",
     "dft_target",
     "paramagnetic T1 target split, preserved for decomposition audits"},
    {"per_atom_substrate_target_para_T2",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "paramagnetic T2 target split"},
    {"per_atom_substrate_features_classical",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomClassicalCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "mixed",
     "classical_features",
     "dense classical mechanism features; column metadata is in per_atom_substrate_column_specs.json"},
    {"per_atom_substrate_features_ring_paths",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomRingPathCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "mixed",
     "ring_path_features",
     "ring-path feature block, including Biot-Savart/Hausch-Mallion/path families used by stage-2 ring laws"},
    {"per_atom_substrate_features_method_paths",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomMethodPathCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "mixed",
     "method_path_features",
     "method-specific path features for MOPAC, water/field, and related mechanism paths"},
    {"per_atom_substrate_features_hbond_conditioning",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomHbondConditioningCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "mixed",
     "hbond_conditioning",
     "H-bond / Larsen / pi-quadrupole conditioning features"},
    {"per_atom_substrate_features_conditioning",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomConditioningCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "mixed",
     "conditioning",
     "topology, geometry, support, and reducer conditioning scalars"},
    {"per_atom_substrate_features_dominance",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomDominanceCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "unitless",
     "dominance",
     "per-row dominant mechanism fractions/gaps for stratification and masks"},
    {"per_atom_substrate_partition_bins",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomPartitionBinCols,
     1,
     ReaderOutputDtype::I32,
     "categorical",
     -1,
     false,
     "bin",
     "partition_bins",
     "binned distance/charge/modulation partitions with manifest edges"},
    {"per_atom_substrate_dominance_bins",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomDominanceBinCols,
     1,
     ReaderOutputDtype::I32,
     "categorical",
     -1,
     false,
     "bin",
     "dominance_bins",
     "quintile bins of dominance scalar fractions by stratum"},
    {"per_atom_substrate_driver_modulation_by_atom",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomDriverMagnitudeCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "stddev",
     "driver_modulation",
     "atom-axis Welford standard deviations for driver modulation"},
    {"per_atom_substrate_backbone_audit",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomBackboneAuditCols,
     1,
     ReaderOutputDtype::F64,
     "tabular",
     -1,
     false,
     "mixed",
     "backbone_audit",
     "provenance/QC payload for broad-backbone compatibility audits"},
    {"per_atom_substrate_aimnet2_embedding",
     ReaderOutputProducer::PerAtomSubstrate,
     ReaderOutputAxis::PerAtomRow,
     ReaderOutputRank::Rank2,
     kPerAtomEmbeddingDims,
     1,
     ReaderOutputDtype::F32,
     "256x0e",
     -1,
     false,
     "latent",
     "aimnet2_embedding",
     "AIMNet2 embedding ceiling/latent feature sidecar"},

    {"all_atom_equivariant_target_T2",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "all-atom DFT target T2 in lab frame"},
    {"all_atom_equivariant_target_sigma_iso",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "ppm",
     "dft_target",
     "all-atom DFT isotropic shielding target"},
    {"all_atom_equivariant_target_raw",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank3,
     kReaderMatrixRows,
     kReaderMatrixCols,
     ReaderOutputDtype::F64,
     "3x3",
     2,
     false,
     "ppm",
     "dft_target",
     "full raw lab-frame 3x3 DFT shielding tensor; preserve tensor rank"},
    {"all_atom_equivariant_apbs_efield",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "e/Angstrom^2",
     "apbs_efield",
     "lab-frame APBS E-field vector sidecar"},
    {"all_atom_equivariant_apbs_efg_T2",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "field_gradient",
     "apbs_efg",
     "lab-frame APBS EFG T2 payload aligned to target rows"},
    {"all_atom_equivariant_aimnet2_charge",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "e",
     "aimnet2_charge",
     "AIMNet2 charge feature per target row"},
    {"all_atom_equivariant_aimnet2_charge_response_gradient",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "charge_gradient",
     "aimnet2_crg",
     "AIMNet2 charge-response-gradient vector, not polarizability"},
    {"all_atom_equivariant_aimnet2_charge_response_gradient_scalar",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "charge_gradient",
     "aimnet2_crg",
     "scalar CRG magnitude/summary channel"},
    {"all_atom_equivariant_aimnet2_embedding",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank2,
     kAllAtomEquivariantEmbeddingDims,
     1,
     ReaderOutputDtype::F32,
     "256x0e",
     -1,
     false,
     "latent",
     "aimnet2_embedding",
     "AIMNet2 embedding ceiling/latent feature sidecar"},
    {"all_atom_equivariant_mopac_coulomb_shielding_T2",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "mopac_coulomb",
     "MOPAC Coulomb/field-derived shielding T2 payload"},
    {"all_atom_equivariant_mopac_mc_shielding_T2",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "mopac_mc",
     "MOPAC McConnell shielding T2 payload"},
    {"all_atom_equivariant_mopac_charge_welford_mean",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "e",
     "mopac_charge",
     "MOPAC Welford mean charge sidecar used for charge-source support/reconciliation"},
    {"all_atom_equivariant_mopac_vs_ff14sb_reconciliation",
     ReaderOutputProducer::AllAtomEquivariant,
     ReaderOutputAxis::TargetRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "cosine",
     "mopac_charge_reconciliation",
     "MOPAC-vs-FF14SB charge reconciliation/audit scalar"},

    {"efg_feature_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "field_gradient",
     "apbs_efg",
     "APBS EFG feature transformed to local T2 basis"},
    {"efg_target_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "DFT target T2 in the same local basis as efg_feature_T2"},
    {"efg_feature_lab_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "field_gradient",
     "apbs_efg",
     "APBS EFG T2 in lab frame for frame transform audits"},
    {"efg_target_lab_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "DFT target T2 in lab frame for frame transform audits"},
    {"efg_mopac_coulomb_shielding_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "mopac_coulomb",
     "MOPAC Coulomb EFG-derived shielding T2 in local frame"},
    {"efg_mopac_coulomb_shielding_lab_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "mopac_coulomb",
     "lab-frame audit copy of the MOPAC Coulomb shielding T2"},
    {"efg_mopac_mc_shielding_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "mopac_mc",
     "MOPAC McConnell shielding T2 in local frame"},
    {"efg_mopac_mc_shielding_lab_T2",
     ReaderOutputProducer::Efg,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "mopac_mc",
     "lab-frame audit copy of the MOPAC McConnell shielding T2"},

    {"buckingham_efield_feature_field_local",
     ReaderOutputProducer::BuckinghamEfield,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "electric_field",
     "apbs_efield",
     "APBS E-field vector projected into the local backbone frame"},
    {"buckingham_efield_target_T1_unverified",
     ReaderOutputProducer::BuckinghamEfield,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "ppm",
     "dft_target",
     "DFT T1 target payload for convention audit, labelled unverified"},
    {"buckingham_efield_target_T2",
     ReaderOutputProducer::BuckinghamEfield,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "DFT T2 target payload for audit/comparison completeness"},

    {"aimnet2_features_charge_response_gradient_local",
     ReaderOutputProducer::Aimnet2Features,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "charge_gradient",
     "aimnet2_crg",
     "AIMNet2 CRG vector in local frame"},
    {"aimnet2_features_charge_response_gradient_lab",
     ReaderOutputProducer::Aimnet2Features,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "charge_gradient",
     "aimnet2_crg",
     "AIMNet2 CRG vector in lab frame for frame audits/future fits"},
    {"aimnet2_features_charge_response_gradient_scalar",
     ReaderOutputProducer::Aimnet2Features,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "charge_gradient",
     "aimnet2_crg",
     "scalar CRG summary feature"},
    {"aimnet2_features_embedding",
     ReaderOutputProducer::Aimnet2Features,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kAimnet2FeatureEmbeddingDims,
     1,
     ReaderOutputDtype::F32,
     "256x0e",
     -1,
     false,
     "latent",
     "aimnet2_embedding",
     "AIMNet2 embedding ceiling/latent feature block"},
    {"aimnet2_features_target_local_T2",
     ReaderOutputProducer::Aimnet2Features,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "DFT target T2 in local frame aligned to AIMNet2 feature rows"},
    {"aimnet2_features_target_lab_T2",
     ReaderOutputProducer::Aimnet2Features,
     ReaderOutputAxis::AggregatedRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "dft_target",
     "DFT target T2 in lab frame aligned to AIMNet2 feature rows"},
    {"analysis_atom_sigma_csa_descriptors",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::JsonObject,
     "0e+2e",
     2,
     false,
     "ppm",
     "sigma_total_raw",
     "analysis-object series sigma.csa_descriptors: value-ordered principal values, PAS directors, Haeberlen descriptors, and Maryland skew"},
    {"analysis_atom_molecular_frame",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::JsonObject,
     "3x1e",
     1,
     false,
     "dimensionless",
     "molecular_geometry",
     "analysis-object series molecular_frame: per-step lab-frame axes ported from pas_projection.molecular_frame"},
    {"analysis_atom_sigma_raw_mat3",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank3,
     kReaderMatrixRows,
     kReaderMatrixCols,
     ReaderOutputDtype::F64,
     "3x3",
     2,
     false,
     "ppm",
     "sigma_raw",
     "analysis-object series sigma.total_raw/dia_raw/para_raw: retained raw ORCA 3x3 matrices"},
    {"analysis_atom_sigma_mol_mat3",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank3,
     kReaderMatrixRows,
     kReaderMatrixCols,
     ReaderOutputDtype::F64,
     "3x3",
     2,
     false,
     "ppm",
     "molecular_frame_projection",
     "analysis-object series sigma_mol.total/dia/para: raw sigma matrices projected into the molecular frame"},
    {"analysis_atom_field_sources_vec3",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "V/Å",
     "electric_field",
     "analysis-object field source vectors: field.apbs and field.charge_ff14sb alongside existing MOPAC/legacy FF14SB"},
    {"analysis_atom_field_mol_vec3",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "V/Å",
     "molecular_frame_projection",
     "analysis-object series field_mol.*: field vectors projected into molecular-frame xyz"},
    {"analysis_atom_field_scalar_derivatives",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "V/Å or (V/Å)^2",
     "electric_field_invariant",
     "analysis-object scalar field series field.E_z.*, field.E2.*, field.abs_E.*, and field.abs_E2.*"},
    {"analysis_atom_charge_field_audit_counts",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::I32,
     "0e",
     0,
     false,
     "count",
     "electric_field_audit",
     "analysis-object field.charge_ff14sb source/rejection/missing-charge count series"},
    {"analysis_atom_efg_mol_mat3",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank3,
     kReaderMatrixRows,
     kReaderMatrixCols,
     ReaderOutputDtype::F64,
     "3x3",
     2,
     false,
     "V/Å^2",
     "molecular_frame_projection",
     "analysis-object series efg_mol.apbs/aimnet2: reconstructed EFG T2 projected into molecular-frame matrices"},
    {"analysis_atom_efg_abs_scalar",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "V/Å^2",
     "efg_invariant",
     "analysis-object series efg.abs.apbs/aimnet2: frame-free EFG T2 magnitudes"},
    {"analysis_atom_mopac_coulomb_shielding_T2",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     kReaderT2Cols,
     1,
     ReaderOutputDtype::F64,
     "2e",
     2,
     false,
     "ppm",
     "mopac_coulomb_shielding",
     "analysis-object series shielding.mopac_coulomb and shielding.abs_T2.mopac_coulomb; derived shielding, not raw EFG"},
    {"analysis_atom_ring_per_type_T2",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     40,
     1,
     ReaderOutputDtype::F64,
     "8x2e",
     2,
     false,
     "ppm_T_per_nA or Å^-1",
     "ring_current",
     "analysis-object series bs_per_type_T2 and hm_per_type_T2: full 40-column per-ring-type T2 producer kernels"},
    {"analysis_atom_mcconnell_tensors",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     9,
     1,
     ReaderOutputDtype::F64,
     "0e+1e+2e",
     2,
     false,
     "Å^-3",
     "bond_anisotropy",
     "analysis-object mc_* tensor family, including rhombic peptide C=O and nearest-bond/self/own-bond producer terms"},
    {"analysis_atom_empirical_predictor_tensors",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     9,
     1,
     ReaderOutputDtype::F64,
     "0e+1e+2e",
     2,
     false,
     "ppm",
     "empirical_predictor",
     "analysis-object tripeptide_bb_shielding and larsen_hbond_shielding surfaced as raw producer tensors"},
    {"analysis_atom_structural_scalars",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::F64,
     "0e",
     0,
     false,
     "Å, Å^2, count",
     "local_structure",
     "analysis-object scalar structural series sasa, hbond.count, and ff_pb_radius"},
    {"analysis_atom_hbond_nearest_dir",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank2,
     kReaderVec3Cols,
     1,
     ReaderOutputDtype::F64,
     "1o",
     1,
     true,
     "dimensionless",
     "hbond_geometry",
     "analysis-object hbond.nearest_dir vector series"},
    {"analysis_atom_bond_lengths",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::JsonObject,
     "0e",
     0,
     false,
     "Å",
     "bond_geometry",
     "analysis-object bond.lengths: per-static-bond length series with degenerate-geometry rejection flags and disulfide S-S label"},
    {"analysis_atom_graph_topology",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::JsonObject,
     "0e",
     0,
     false,
     "mixed",
     "graph_topology",
     "analysis-object model.graph_topology: covalent graph descriptors and pinned definitions"},
    {"analysis_atom_substrate_parameters",
     ReaderOutputProducer::AnalysisObject,
     ReaderOutputAxis::AtomRow,
     ReaderOutputRank::Rank1,
     1,
     1,
     ReaderOutputDtype::JsonObject,
     "0e",
     0,
     false,
     "mixed",
     "metadata",
     "analysis-object model.substrate_parameters: cutoffs and literature constants carried as reader-owned values"},
}};

constexpr const ReaderOutputSpec* FindReaderOutputByStem(std::string_view stem) {
    for (std::size_t i = 0; i < kReaderOutputCatalog.size(); ++i) {
        if (kReaderOutputCatalog[i].stem == stem) return &kReaderOutputCatalog[i];
    }
    return nullptr;
}

constexpr std::size_t ReaderOutputTrailingElements(const ReaderOutputSpec& spec) {
    switch (spec.rank) {
    case ReaderOutputRank::Rank1:
        return 1;
    case ReaderOutputRank::Rank2:
        return spec.extent0;
    case ReaderOutputRank::Rank3:
        return spec.extent0 * spec.extent1;
    }
    return 0;
}

constexpr std::string_view ReaderOutputProducerName(ReaderOutputProducer producer) {
    switch (producer) {
    case ReaderOutputProducer::RingCurrent:
        return "RingCurrentNeighborhood/RecordSink";
    case ReaderOutputProducer::McConnell:
        return "McConnellNeighborhood/RecordSink";
    case ReaderOutputProducer::ChargeDipole:
        return "ChargeDipoleNeighborhood/RecordSink";
    case ReaderOutputProducer::BroadBackbone:
        return "BroadBackboneSink";
    case ReaderOutputProducer::PerAtomSubstrate:
        return "PerAtomSubstrate";
    case ReaderOutputProducer::AllAtomEquivariant:
        return "AllAtomEquivariantSink";
    case ReaderOutputProducer::Efg:
        return "EfgFeatureSink";
    case ReaderOutputProducer::BuckinghamEfield:
        return "BuckinghamEfieldSink";
    case ReaderOutputProducer::Aimnet2Features:
        return "Aimnet2FeatureSink";
    case ReaderOutputProducer::AnalysisObject:
        return "AnalysisAtom";
    }
    return "unknown";
}

}  // namespace h5reader::rediscover
