#pragma once
//
// The force field fixes both partial charges and the electrostatic radius
// model, so charge sources are typed instead of path-string dispatch.
// ChargeAssignmentResult consumes the resulting per-atom rows.
//

#include "Types.h"
#include <string>
#include <vector>
#include <utility>

namespace nmr {

class Protein;
class ProteinConformation;


// Force field identity. Recorded in ProteinBuildContext as provenance.
enum class ForceField {
    Amber_ff14SB,
    Amber_ff19SB,
    CHARMM36m,
    Unknown
};

inline const char* ForceFieldName(ForceField ff) {
    switch (ff) {
        case ForceField::Amber_ff14SB: return "ff14SB";
        case ForceField::Amber_ff19SB: return "ff19SB";
        case ForceField::CHARMM36m:    return "CHARMM36m";
        case ForceField::Unknown:      return "unknown";
    }
    return "unknown";
}


// Where the loaded force-field charge/PB-radius values came from.
// Upstream PRMTOPs and PRMTOPs generated at run time remain distinct
// provenance paths even though both are AMBER topology files.
enum class ChargeModelKind {
    AmberPrmtop,            // upstream PRMTOP via PrmtopChargeSource
    AmberPreparedPrmtop,    // PRMTOP generated by AmberPreparedChargeSource
    GromacsTpr,             // CHARMM/GROMACS TPR (placeholder PB radii)
    Ff14SBParamFile,        // ff14SB flat parameter file
    Preloaded,              // pre-loaded charges supplied by caller
    Unknown
};

inline const char* ChargeModelKindName(ChargeModelKind kind) {
    switch (kind) {
        case ChargeModelKind::AmberPrmtop:         return "AmberPrmtop";
        case ChargeModelKind::AmberPreparedPrmtop: return "AmberPreparedPrmtop";
        case ChargeModelKind::GromacsTpr:          return "GromacsTpr";
        case ChargeModelKind::Ff14SBParamFile:     return "Ff14SBParamFile";
        case ChargeModelKind::Preloaded:           return "Preloaded";
        case ChargeModelKind::Unknown:             return "Unknown";
    }
    return "Unknown";
}


// Per-atom charge and Poisson-Boltzmann radius from whatever source.
enum class ChargeAssignmentStatus {
    Matched,
    PlaceholderPbRadius,
    Missing
};

struct AtomChargeRadius {
    double partial_charge = 0.0;    // elementary charges (e)
    double pb_radius = 0.0;         // Angstroms, electrostatic/PB radius
    ChargeAssignmentStatus status = ChargeAssignmentStatus::Matched;
};

// GROMACS/CHARMM TPR readback supplies real charges but only placeholder
// PB radii; APBS output from that path is not a standard charge/radius model.
inline constexpr double kCompatibilityPlaceholderPbRadiusAngstrom = 1.5;


// Abstract charge source. Implementations return one row per atom in the
// ProteinConformation atom order.
class ChargeSource {
public:
    virtual ~ChargeSource() = default;

    // Which force field produced these charges.
    virtual ForceField SourceForceField() const = 0;

    // Which loader/source format produced the table.
    virtual ChargeModelKind Kind() const { return ChargeModelKind::Unknown; }

    // Human-readable description for logging.
    virtual std::string Describe() const = 0;

    // Empty vector on failure (error reported via error_out).
    virtual std::vector<AtomChargeRadius> LoadCharges(
        const Protein& protein,
        const ProteinConformation& conf,
        std::string& error_out) const = 0;
};


// ff14SB from the flat parameter file.
class ParamFileChargeSource : public ChargeSource {
public:
    explicit ParamFileChargeSource(const std::string& param_file_path)
        : path_(param_file_path) {}

    ForceField SourceForceField() const override { return ForceField::Amber_ff14SB; }
    ChargeModelKind Kind() const override { return ChargeModelKind::Ff14SBParamFile; }
    std::string Describe() const override { return "ff14SB:" + path_; }

    std::vector<AtomChargeRadius> LoadCharges(
        const Protein& protein,
        const ProteinConformation& conf,
        std::string& error_out) const override;

private:
    std::string path_;
};


// AMBER PRMTOP reader. %FLAG CHARGE uses AMBER internal units; %FLAG RADII
// stores PB radii in Angstroms.
class PrmtopChargeSource : public ChargeSource {
public:
    explicit PrmtopChargeSource(const std::string& prmtop_path,
                                ForceField ff = ForceField::Amber_ff14SB)
        : path_(prmtop_path), ff_(ff) {}

    ForceField SourceForceField() const override { return ff_; }
    ChargeModelKind Kind() const override { return ChargeModelKind::AmberPrmtop; }
    std::string Describe() const override {
        return std::string(ForceFieldName(ff_)) + ":prmtop:" + path_;
    }

    std::vector<AtomChargeRadius> LoadCharges(
        const Protein& protein,
        const ProteinConformation& conf,
        std::string& error_out) const override;

private:
    std::string path_;
    ForceField ff_;
};


// Pre-loaded per-atom values, already matched to the ProteinConformation order.
class PreloadedChargeSource : public ChargeSource {
public:
    PreloadedChargeSource(std::vector<AtomChargeRadius> charges,
                          ForceField ff)
        : charges_(std::move(charges)), ff_(ff) {}

    ForceField SourceForceField() const override { return ff_; }
    ChargeModelKind Kind() const override { return ChargeModelKind::Preloaded; }
    std::string Describe() const override {
        return std::string(ForceFieldName(ff_)) + ":preloaded";
    }

    std::vector<AtomChargeRadius> LoadCharges(
        const Protein& protein,
        const ProteinConformation& conf,
        std::string& error_out) const override;

private:
    std::vector<AtomChargeRadius> charges_;
    ForceField ff_;
};


}  // namespace nmr
